#!/usr/bin/env bash

# Replace values inside < >

date=$(date -u +%Y-%m-%d.%H-%M-%S)
name=<app-name>
aws_endpoint=<https://s3.amazonaws.com>
aws_bucket=<aws-bucket>
container_name=<postgres-container-name>
database_name=<database-name>

docker exec -t ${container_name} pg_dump -w -Fc -O -U postgres ${database_name} | gzip | aws --endpoint-url ${aws_endpoint} s3 cp - s3://${aws_bucket}/${name}-postgres-backup-${date}.sql.gz

aws --endpoint-url ${aws_endpoint} s3 ls ${aws_bucket}/ | while read -r line;
  do
    create_date=`echo $line|awk {'print $1" "$2'}`
    create_date=`date -d"$create_date" +%s`
    older_than=`date --date "10 days ago" +%s`

    if [[ $create_date -lt $older_than ]]
      then
        file_name=`echo $line|awk {'print $4'}`

        if [[ $file_name == *"-postgres-backup-"* ]]
          then
            aws --endpoint-url ${aws_endpoint} s3 rm ${aws_bucket}/$file_name
        fi
    fi
  done;
